
import { Inter } from 'next/font/google'
import { Providers } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children}:{children: React.ReactNode}) {
  return (
    <html lang="pt-br">
      <head/>
      <body style={{overflow:'hidden'}}>
       <Providers>{children}</Providers>
        </body>
    </html>
  )
}
